name: dargon2_flutter_mobile
description: The mobile (iOS & Android) platform implementation of dargon2_flutter
version: 3.3.0
homepage: https://github.com/tmthecoder/dargon2/
repository: https://github.com/tmthecoder/dargon2/blob/main/dargon2_flutter/dargon2_flutter_mobile

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dargon2_core: 
    git:
      url: https://github.com/ryanaidilp/dargon2.git
      ref: main
      path: dargon2_core
  dargon2_flutter_platform_interface: 
    git:
      url: https://github.com/ryanaidilp/dargon2.git
      ref: main
      path: dargon2_flutter/dargon2_flutter_platform_interface
  dargon2_interface: 
    git:
      url: https://github.com/ryanaidilp/dargon2.git
      ref: main
      path: dargon2_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    implements: dargon2_flutter
    platforms:
      android:
        dartPluginClass: DArgon2Mobile
        ffiPlugin: true
      ios:
        dartPluginClass: DArgon2Mobile
        ffiPlugin: true
