name: dargon2_core
description: The bindings for argon2's C reference library. Does not include the library loading itself.
version: 2.1.1
homepage: https://github.com/tmthecoder/dargon2/blob/main/dargon2_core
repository: https://github.com/tmthecoder/dargon2/

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  ffi: '^2.0.1'
  dargon2_interface: 
    git:
      url: https://github.com/ryanaidilp/dargon2.git
      ref: main
      path: dargon2_interface

dev_dependencies:
  lints: ^2.0.0
  pedantic: ^1.10.0
  test: ^1.16.0
