name: dargon2
description: Provides bindings for hashing and verifying with Argon2, the winner of the Password Hashing Competition.
version: 3.2.1
homepage: https://github.com/tmthecoder/dargon2/blob/main/dargon2
repository: https://github.com/tmthecoder/dargon2

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dargon2_core: 
    git:
      url: https://github.com/ryanaidilp/dargon2.git
      ref: main
      path: dargon2_core

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

